### ISSUE TITLE
trait bound `ResourceFiles: HttpServiceFactory` is not satisfied

### ISSUE THREAD

**Issue by kkharji** [kilork/actix-web-static-files#34]
Hey @kilork, I'm trying to use your awesome crate but I'm getting an error saying `the trait 'HttpServiceFactory' is not implemented for `ResourceFiles`

my Cargo.toml:

```toml
[package]
name = "server"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web-static-files = "3.0.5"
actix-web = "4.0.0-beta.3"  

[build-dependencies]
actix-web-static-files = "3.0.5"
```

main.rs

```rust
use actix_web::{App, HttpServer};
use actix_web_static_files;

include!(concat!(env!("OUT_DIR"), "/generated.rs"));

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(move || {
        let generated = generate();

        App::new().service(actix_web_static_files::ResourceFiles::new(
            "/static", generated,
        ))
    })
    .bind("127.0.0.1:8080")?
    .run()
    .await
}
```

build.rs
```rust
use actix_web_static_files::generate_resources;
use std::{env, path::Path};

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let generated_filename = Path::new(&out_dir).join("generated.rs");
    generate_resources("./static", None, generated_filename, "generate")
        .expect("can't collect resources");
}

```
